version: '3.8'

services:
  ds-finder:
    container_name: ds-finder
    build: .
    volumes:
      - "./src:/app"
      - "./testset:/app/tmp/testset"
    stdin_open: true
    tty: true
    restart: always