services:
  ds-dev:
    container_name: ds-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - "./src:/app"
      - "./testset:/app/tmp/testset"
      - "./real-instances:/app/tmp/instances"
    stdin_open: true
    tty: true
    restart: always
  ds-build:
    container_name: ds-build
    build:
      context: .
      dockerfile: build.Dockerfile
    platform: linux/amd64
    volumes:
      - "./src:/app"
    tty: true
    stdin_open: true
    restart: no
    command: sh -c "cmake -DCMAKE_BUILD_TYPE=Static . && make binary_solution"