version: '3.8'

services:
  ds-dev:
    container_name: ds-dev
    build:
      context: .
      dockerfile: dev.Dockerfile
    volumes:
      - "./src:/app"
      - "./testset:/app/tmp/testset"
      - "./real-instances:/app/tmp/instances"
    stdin_open: true
    tty: true
    restart: always
  ds-builder:
    container_name: ds-builder
    build:
      context: .
      dockerfile: builder.Dockerfile
    platform: linux/amd64
    volumes:
      - "./src:/app"
    tty: true
    stdin_open: true
    restart: no
    command: make binary_solution