name: Dockerized Compile

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]
  
jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: . 
          load: true
          tags: ds-finder:latest

      - name: Running 'make'
        run: |
          docker run \
            -v ${{ github.workspace }}:/app \
            -w /app \
            ds-finder:latest \
            make